// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_MediaControls();
Q_GHS_KEEP_REFERENCE(qml_register_types_MediaControls)

class MediaControlsPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    MediaControlsPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_MediaControls;
        Q_UNUSED(registration)
    }
};



#include "MediaControlsplugin_MediaControlsPlugin.moc"
