// This file is autogenerated by CMake. Do not edit.

#include <QtQml/qqmlextensionplugin.h>

extern void qml_register_types_Button();
Q_GHS_KEEP_REFERENCE(qml_register_types_Button)

class ButtonPlugin : public QQmlEngineExtensionPlugin
{
    Q_OBJECT
    Q_PLUGIN_METADATA(IID QQmlEngineExtensionInterface_iid)

public:
    ButtonPlugin(QObject *parent = nullptr) : QQmlEngineExtensionPlugin(parent)
    {
        volatile auto registration = &qml_register_types_Button;
        Q_UNUSED(registration)
    }
};



#include "MyButtonplugin_ButtonPlugin.moc"
